openapi: 3.0.0
info:
  version: 1.0.0
  title: Accounts
  description: Returns a list of users and their information
servers:
  - url: https://tigerchow.com/v1
paths:
  /account:
    get:
      description: Returns a list of users           
      responses:
        '200': 
          description: Successful returned a list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  #  ----- Added line  --------------------------------
                  $ref: '#/components/schemas/Account'
                  #  ---- /Added line  --------------------------------
                  #  ---- /Added line  --------------------------------
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
    post:
      description: Lets a user post a new artist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - username
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                username:
                  type: integer
                password:
                  type: string
                user_id:
                  type: string

      responses:
        '200':
          description: Successfully created a new artist

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Account:
      type: object
      required:
        - username
      properties:
        first_name:
          type: string
        last_name:
          type: string
        username:
          type: string
        password:
          type: string
        user_id:
          type: string
          
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object 
            properties:
              message:
                type: string
      