openapi: 3.0.0
info:
  version: 1.0.0
  title: Events
  description: Returns a list of events and post events

servers:
  - url: https://tigerchow.com/v1

security:
  - BasicAuth: []
paths:
  /events:
    get:
      description: Returns a list of events           
      responses:
        '200': 
          description: Successful returned a list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  #  ----- Added line  --------------------------------
                  $ref: '#/components/schemas/Events'
                  #  ---- /Added line  --------------------------------
                  #  ---- /Added line  --------------------------------
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
    post:
      description: Lets a user post a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - username
              properties:
                event_id:
                  type: string
                event_name:
                  type: string
                event_date:
                  type: integer
                event_time:
                  type: string
                event_description:
                  type: string

      responses:
        '200':
          description: Successfully created a new event

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Events:
      type: object
      required:
        - username
      properties:
        event_id:
          type: string
        event_name:
          type: string
        event_date:
          type: string
        event_time:
          type: string
        event_description:
          type: string
          
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object 
            properties:
              message:
                type: string